version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports: ['3307:3306']
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  php:
    build:
      context: ./docker/php
    ports: ['9000:9000']
    environment:
      # Debug options for developers
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1 idekey=PHPSTORM remote_autostart=off remote_handler=dbgp remote_port=9003"
      PHP_IDE_CONFIG: serverName=Docker
    volumes: ['./symfony/:/var/www/symfony:cached']
  nginx:
    build: ./docker/nginx
    ports: ['81:80']
    volumes: ['./symfony/:/var/www/symfony:cached']