version: '3.7'
services:
  mysql:
    image: mysql:5.7
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports: ['3307:3306']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - "./docker/mysqldata:/var/lib/mysql"
  php:
    build:
      context: ./docker/php
    ports: ['9000:9000']
    environment:
      # Debug options for developers
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1 idekey=PHPSTORM remote_autostart=off remote_handler=dbgp remote_port=9003"
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - ./symfony:/var/www/symfony:cached
      - ./docker/logs/symfony:/var/www/symfony/var/log:cached
  nginx:
    build: ./docker/nginx
    ports: ['81:80']
    depends_on:
      - php
    volumes:
      - ./docker/logs/nginx:/var/log/nginx:cached
      - ./symfony:/var/www/symfony:cached